version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jonnajojo15
      POSTGRES_DB: blog_api_development

    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:jonnajojo15@db:5432/blog_api_development
      - REDIS_URL=redis://redis:6379/0

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis